### ISSUE TITLE
async function populateVideoInfos

### ISSUE THREAD

**Issue by Bilters** [cathect/skillshare-downloader#1]
```
async function populateVideoInfos(accID, pk, sess) {
      ^^^^^^^^
SyntaxError: Unexpected token function
```
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

This is the error i get when i run node app

I've populated the config.json correctly (without the quotes - and paying account), and the course url, nothing else. And i've installed the npm packages.

**Comment by cathect** [comment]
What node version do you have? Async functions are not supported by node versions older than 7.6. You can check your node version by typing `node -v` in the CLI. If it's any earlier than 7.6 you should download the latest version from https://nodejs.org/en/download/

**Comment by Bilters** [comment]
Yes that was the issue. Thanks for the swift response!
