### ISSUE TITLE
Keeps Returning Null/ No Video ID

### ISSUE THREAD

**Issue by foong** [cathect/skillshare-downloader#2]
TypeError: Cannot read property 'toString' of null
    at C:\Users\Wee Jia Foong\Downloads\skillshare-downloader-master\api.js:50:16
    at new Promise (<anonymous>)
    at Object.exports.getPolicyKey (C:\Users\Wee Jia Foong\Downloads\skillshare-downloader-master\api.js:42:10)
    at api.getBaseInfo.then.info (C:\Users\Wee Jia Foong\Downloads\skillshare-downloader-master\app.js:16:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
null
No Video ID for  Project
No Video ID for  Poster overview
No Video ID for  Creating Gradient
No Video ID for  Creating Gradient Shapes
No Video ID for  Finalizing

Not sure if i have done everything right.
Could you elaborate more on the session cookie part? Do I just copy and paste the whole string from the console?

Running on v10.15.3

**Comment by cathect** [comment]
Looking into it now, sorry for the wait

**Comment by hashblen** [comment]
same for me :c

**Comment by Flashminat0** [comment]
any fix?
